package tests

import (
	"testing"

	"github.com/asentientbanana/uz/unzip"
)

func TestUnzip(t *testing.T) {
	unzip.Unzip_Single_Book(
		// "/home/petar/bigboy/Manga/Vagabond/# 1.cbz",
		"/home/petar/bigboy/Manga/OnePiece/Vol. 95.cbz",
		"/home/petar/Documents/mangakolekt/current")
}
func TestUnzipCovers(t *testing.T) {

	// unzip.Unzip_covers_from_dir(strings.Join(targetFiles, "&&"),
	// 	"/home/petar/Videos/target")
}

var targetFiles = []string{
	"/home/petar/bigboy/Manga/OnePiece/Vol. 01.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 02.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 03.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 04.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 05.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 06.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 07.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 08.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 09.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 10.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 11.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 12.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 13.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 14.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 15.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 16.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 17.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 18.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 19.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 20.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 21.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 22.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 23.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 24.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 25.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 26.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 27.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 28.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 29.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 30.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 31.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 32.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 33.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 34.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 35.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 36.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 37.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 38.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 39.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 40.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 41.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 42.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 43.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 44.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 45.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 46.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 47.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 48.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 49.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 50.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 51.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 52.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 53.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 54.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 55.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 56.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 57.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 58.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 59.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 60.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 61.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 62.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 63.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 64.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 65.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 66.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 67.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 68.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 69.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 70.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 71.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 72.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 73.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 74.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 75.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 76.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 77.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 78.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 79.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 80.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 81.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 82.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 83.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 84.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 85.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 86.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 87.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 88.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 89.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 90.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 91.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 92.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 93.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 94.cbz",
	"/home/petar/bigboy/Manga/OnePiece/Vol. 95.cbz",
}
